/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        rose: {
          50: '#FFF5F7',
          100: '#FFE0E6',
          200: '#FFC1CC',
          300: '#FF9AAF',
          400: '#F97B8A',
          500: '#E85D70',
          600: '#C9445A',
          700: '#A33347',
          800: '#7A2738',
          900: '#521A25',
        },
        cream: {
          50: '#FFFCF9',
          100: '#FFF8F3',
        },
        'warm-gray': {
          50: '#FAF8F6',
          100: '#F2EDEA',
          200: '#E2DAD5',
          300: '#C9BDB5',
          400: '#A8998E',
          500: '#8C7A70',
          600: '#6B5D54',
          700: '#4D423C',
          800: '#332C28',
          900: '#1E1A18',
        },
        dark: {
          bg: '#1A1518',
          surface: '#231E21',
          elevated: '#2C2529',
          border: '#3A3236',
          text: '#F0EAE6',
          'text-secondary': '#A8998E',
          rose: '#F97B8A',
          'rose-soft': '#3D2830',
        },
        success: '#7EB89A',
        'success-light': '#E8F5EE',
        warning: '#E8A838',
        'warning-light': '#FFF3E0',
        error: '#D4626A',
        'error-light': '#FDE8E9',
        info: '#6BA3D6',
        'info-light': '#EBF4FA',
        gold: '#D4A574',
        'gold-light': '#FBF3EB',
        platinum: '#B8C4CE',
      },
      fontFamily: {
        serif: ['Playfair Display', 'Georgia', 'serif'],
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
        'space-16': '64px',
        'space-20': '80px',
        'space-24': '96px',
        'space-32': '128px',
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        '2xl': '20px',
        '3xl': '24px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        card: '0 2px 12px rgba(30,26,24,0.06), 0 0 1px rgba(30,26,24,0.08)',
        'card-hover': '0 12px 32px rgba(30,26,24,0.1)',
        nav: '0 2px 20px rgba(0,0,0,0.06)',
        cta: '0 4px 16px rgba(233,93,112,0.3), 0 1px 3px rgba(233,93,112,0.15)',
        'cta-hover': '0 8px 24px rgba(233,93,112,0.35)',
        'gold-cta': '0 4px 16px rgba(212,165,116,0.3)',
        modal: '0 24px 64px rgba(30,26,24,0.15)',
        dropdown: '0 8px 32px rgba(0,0,0,0.1)',
        input: '0 0 0 4px rgba(233,93,112,0.1)',
        'hero-mockup': '0 32px 64px rgba(30,26,24,0.12), 0 0 1px rgba(30,26,24,0.1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(40px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-scale": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-60px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(60px)" },
          "100%": { opacity: "1", transform: "X(0)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-15px)" },
        },
        "float-mini": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "fade-up": "fade-up 0.6s ease-out forwards",
        "fade-scale": "fade-scale 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "slide-in-left": "slide-in-left 0.7s ease-out forwards",
        "slide-in-right": "slide-in-right 0.7s ease-out forwards",
        "float": "float 6s ease-in-out infinite alternate",
        "float-mini": "float-mini 4s ease-in-out infinite alternate",
        "shimmer": "shimmer 3s linear infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
