import { useMemo, useState } from 'react';
import { CheckCircle2, Clock3, FlaskConical, Flag, RotateCcw, Sparkles } from 'lucide-react';

const questions = [
  { id: 1, area: 'Measurement', difficulty: 'Foundational', prompt: 'A practitioner wants a measure that captures how long a behavior lasts from onset to offset. Which measurement dimension best fits?', options: ['Frequency', 'Duration', 'Latency', 'Interresponse time'], answer: 1, why: 'Duration measures the amount of time a behavior occurs from onset to offset.' },
  { id: 2, area: 'Experimental Design', difficulty: 'Intermediate', prompt: 'Which feature most directly strengthens the demonstration of a functional relation in a reversal design?', options: ['Collecting only baseline data', 'Systematically withdrawing and reintroducing the independent variable', 'Increasing the number of observers', 'Using only permanent-product measures'], answer: 1, why: 'Repeated introduction and withdrawal of the independent variable demonstrates whether behavior changes reliably with that manipulation.' },
  { id: 3, area: 'Ethics & Professional Practice', difficulty: 'Applied', prompt: 'A supervisee is uncertain whether a case discussion contains enough detail to identify a client. What is the safest educational-platform action?', options: ['Post it and remove the name', 'Share only with a large group', 'Further de-identify the information or avoid posting it', 'Replace the client name with initials only'], answer: 2, why: 'Removing a name alone may not sufficiently de-identify private information. The safer choice is to further de-identify or not share it.' },
];

export default function ExamLab() {
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [flagged, setFlagged] = useState<number[]>([]);
  const [submitted, setSubmitted] = useState(false);
  const q = questions[index];
  const score = useMemo(() => questions.reduce((sum, item) => sum + (answers[item.id] === item.answer ? 1 : 0), 0), [answers]);

  const reset = () => { setIndex(0); setAnswers({}); setFlagged([]); setSubmitted(false); };

  return <div className="min-h-[100dvh] bg-[#FFFCF9] px-4 py-8 dark:bg-[#171412]"><div className="mx-auto max-w-6xl">
    <header className="mb-6"><div className="flex items-center gap-2 text-sm font-bold text-[#E85D70]"><FlaskConical size={17} /> Exam Lab</div><h1 className="mt-2 font-serif text-4xl font-semibold text-[#332C28] dark:text-white">Practice like the test matters. Learn like every miss is useful.</h1><p className="mt-2 max-w-3xl text-[#6B5D54] dark:text-[#CFC4BE]">Full simulations, adaptive practice, content-area drills, timing tools, and AI coaching live here. This diagnostic uses original unofficial practice questions and does not reproduce actual examination items.</p></header>

    {!submitted ? <div className="grid gap-5 lg:grid-cols-[1fr_300px]">
      <section className="rounded-[30px] border border-[#F2EDEA] bg-white p-6 lg:p-8 dark:border-white/10 dark:bg-[#211D1A]"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-[#A8998E]">Question {index + 1} of {questions.length}</div><div className="mt-1 text-xs text-[#A8998E]">{q.area} • {q.difficulty}</div></div><button onClick={() => setFlagged((f) => f.includes(q.id) ? f.filter((id) => id !== q.id) : [...f, q.id])} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold ${flagged.includes(q.id) ? 'bg-[#FFF3E0] text-[#B77722]' : 'bg-[#FAF8F6] text-[#6B5D54] dark:bg-white/5 dark:text-[#CFC4BE]'}`}><Flag size={15} /> {flagged.includes(q.id) ? 'Flagged' : 'Flag for review'}</button></div><h2 className="mt-6 font-serif text-2xl font-semibold leading-9 text-[#332C28] dark:text-white">{q.prompt}</h2><div className="mt-6 space-y-3">{q.options.map((option, i) => <button key={option} onClick={() => setAnswers({ ...answers, [q.id]: i })} className={`w-full rounded-2xl border p-4 text-left text-sm font-medium transition ${answers[q.id] === i ? 'border-[#E85D70] bg-[#FFF4F6] text-[#D94D62] dark:bg-[#E85D70]/10' : 'border-[#E8E0DB] text-[#4D423C] hover:border-[#E85D70]/50 dark:border-white/10 dark:text-[#E7DED9]'}`}><span className="mr-3 font-mono text-[#A8998E]">{String.fromCharCode(65 + i)}.</span>{option}</button>)}</div><div className="mt-7 flex items-center justify-between"><button disabled={index === 0} onClick={() => setIndex(index - 1)} className="rounded-xl border border-[#E2DAD5] px-4 py-2.5 text-sm font-semibold text-[#6B5D54] disabled:opacity-30 dark:border-white/10 dark:text-[#CFC4BE]">Previous</button>{index < questions.length - 1 ? <button onClick={() => setIndex(index + 1)} className="rounded-xl bg-[#332C28] px-5 py-2.5 text-sm font-bold text-white dark:bg-[#E85D70]">Next question</button> : <button onClick={() => setSubmitted(true)} className="rounded-xl bg-[#E85D70] px-5 py-2.5 text-sm font-bold text-white">Submit diagnostic</button>}</div></section>
      <aside className="space-y-4"><div className="rounded-[26px] bg-[#332C28] p-5 text-white dark:bg-[#211D1A] dark:ring-1 dark:ring-white/10"><div className="flex items-center gap-2 text-sm font-bold text-[#F4C895]"><Clock3 size={16} /> Practice mode</div><div className="mt-3 font-serif text-2xl font-semibold">Untimed diagnostic</div><p className="mt-2 text-sm text-white/65">Focus on reasoning first. Full Exam Lab can support timed, untimed, adaptive, and content-area modes.</p></div><div className="rounded-[26px] border border-[#F2EDEA] bg-white p-5 dark:border-white/10 dark:bg-[#211D1A]"><div className="text-xs font-bold uppercase tracking-[.16em] text-[#A8998E]">Navigation</div><div className="mt-3 grid grid-cols-5 gap-2">{questions.map((item, i) => <button key={item.id} onClick={() => setIndex(i)} className={`h-10 rounded-xl text-sm font-bold ${index === i ? 'bg-[#E85D70] text-white' : answers[item.id] !== undefined ? 'bg-[#E8F5EE] text-[#4B8C69]' : 'bg-[#FAF8F6] text-[#6B5D54] dark:bg-white/5 dark:text-[#CFC4BE]'}`}>{i + 1}</button>)}</div></div></aside>
    </div> : <section className="rounded-[32px] border border-[#F2EDEA] bg-white p-7 dark:border-white/10 dark:bg-[#211D1A]"><div className="flex items-center gap-2 text-sm font-bold text-[#5FA37E]"><CheckCircle2 size={17} /> Diagnostic complete</div><h2 className="mt-2 font-serif text-4xl font-semibold text-[#332C28] dark:text-white">{Math.round((score / questions.length) * 100)}% overall</h2><p className="mt-2 text-[#6B5D54] dark:text-[#CFC4BE]">Baker’s coaching view turns each miss into a concept lesson, follow-up question, and targeted practice plan.</p><div className="mt-7 space-y-4">{questions.map((item) => { const correct = answers[item.id] === item.answer; return <div key={item.id} className={`rounded-2xl border p-5 ${correct ? 'border-[#B7DEC7] bg-[#F3FBF6]' : 'border-[#F0D5DA] bg-[#FFF7F8]'} dark:bg-white/5 dark:border-white/10`}><div className="flex items-center gap-2 text-sm font-bold"><span className={correct ? 'text-[#4B8C69]' : 'text-[#C9445A]'}>{correct ? 'Correct' : 'Needs review'}</span><span className="text-[#A8998E]">• {item.area}</span></div><div className="mt-2 text-sm font-semibold text-[#332C28] dark:text-white">{item.prompt}</div><p className="mt-2 text-sm leading-6 text-[#6B5D54] dark:text-[#CFC4BE]">{item.why}</p></div>; })}</div><div className="mt-6 flex flex-wrap gap-3"><button onClick={reset} className="inline-flex items-center gap-2 rounded-xl border border-[#E2DAD5] px-4 py-2.5 text-sm font-semibold text-[#6B5D54] dark:border-white/10 dark:text-[#CFC4BE]"><RotateCcw size={15} /> Retake</button><button className="inline-flex items-center gap-2 rounded-xl bg-[#E85D70] px-4 py-2.5 text-sm font-bold text-white"><Sparkles size={15} /> Build my weak-area plan</button></div></section>}
  </div></div>;
}
