import { useMemo, useState } from 'react';
import { Bookmark, FileText, Filter, Library, Search } from 'lucide-react';

const resources = [
  { id: 'r1', title: 'Fieldwork Organization Checklist', stage: 'Fieldwork', topic: 'Documentation', format: 'Checklist', difficulty: 'Foundational', time: '8 min', desc: 'A clean checklist for organizing supervision, monthly forms, supporting notes, and audit-ready documentation.' },
  { id: 'r2', title: 'Restricted vs. Unrestricted Study Guide', stage: 'Fieldwork', topic: 'Fieldwork', format: 'Study guide', difficulty: 'Foundational', time: '12 min', desc: 'A plain-language review framework with examples, non-examples, and questions to take to your supervisor.' },
  { id: 'r3', title: 'Ethics Scenario Workbook', stage: 'Exam prep', topic: 'Ethics', format: 'Worksheet', difficulty: 'Intermediate', time: '25 min', desc: 'Original practice scenarios designed to strengthen ethical reasoning without reproducing examination items.' },
  { id: 'r4', title: 'BCBA Exam Week Planner', stage: 'Exam prep', topic: 'Study strategy', format: 'Schedule', difficulty: 'Foundational', time: '10 min', desc: 'Plan review blocks, recovery time, sleep, practice sets, and the final 72 hours before your test date.' },
  { id: 'r5', title: 'Supervision Meeting Agenda', stage: 'Fieldwork', topic: 'Supervision', format: 'Template', difficulty: 'Foundational', time: '5 min', desc: 'A reusable agenda for questions, feedback, observation, next actions, and documentation follow-up.' },
  { id: 'r6', title: 'Behavior-Analytic Interview Prep', stage: 'Career', topic: 'Career', format: 'Guide', difficulty: 'Intermediate', time: '20 min', desc: 'Prepare concise stories about collaboration, data, ethics, communication, supervision, and professional growth.' },
  { id: 'r7', title: 'Measurement Flashcard Pack', stage: 'Exam prep', topic: 'Measurement', format: 'Flashcards', difficulty: 'Foundational', time: '15 min', desc: 'A focused review of common measurement dimensions, examples, and discriminations.' },
  { id: 'r8', title: 'Research Reading Notes Template', stage: 'Coursework', topic: 'Research', format: 'Template', difficulty: 'Intermediate', time: '7 min', desc: 'Capture research questions, methods, findings, limitations, and how a paper connects to your coursework.' },
];

export default function ResourceVault() {
  const [query, setQuery] = useState('');
  const [stage, setStage] = useState('All stages');
  const [saved, setSaved] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('fieldworkByBaker:resourceSaves:v1') || '[]'); } catch { return []; } });
  const stages = ['All stages', ...Array.from(new Set(resources.map((r) => r.stage)))];
  const visible = useMemo(() => resources.filter((r) => (stage === 'All stages' || r.stage === stage) && `${r.title} ${r.topic} ${r.format} ${r.desc}`.toLowerCase().includes(query.toLowerCase())), [query, stage]);
  const toggle = (id: string) => { const next = saved.includes(id) ? saved.filter((x) => x !== id) : [...saved, id]; setSaved(next); localStorage.setItem('fieldworkByBaker:resourceSaves:v1', JSON.stringify(next)); };

  return <div className="min-h-[100dvh] bg-[#FFFCF9] px-4 py-8 dark:bg-[#171412]"><div className="mx-auto max-w-7xl">
    <header className="mb-6"><div className="flex items-center gap-2 text-sm font-bold text-[#E85D70]"><Library size={17} /> Resource Vault</div><h1 className="mt-2 font-serif text-4xl font-semibold text-[#332C28] dark:text-white">Everything worth keeping, easy to find again.</h1><p className="mt-2 max-w-3xl text-[#6B5D54] dark:text-[#CFC4BE]">Study guides, flashcards, templates, checklists, ethics scenarios, career tools, research notes, and fieldwork resources—searchable by where you are in the journey.</p></header>
    <div className="mb-6 grid gap-3 md:grid-cols-[1fr_220px]"><div className="relative"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#A8998E]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search the vault" className="w-full rounded-2xl border border-[#E2DAD5] bg-white py-3 pl-11 pr-4 text-sm text-[#332C28] dark:border-white/10 dark:bg-[#211D1A] dark:text-white" /></div><label className="relative"><Filter size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#A8998E]" /><select value={stage} onChange={(e) => setStage(e.target.value)} className="w-full appearance-none rounded-2xl border border-[#E2DAD5] bg-white py-3 pl-11 pr-4 text-sm text-[#332C28] dark:border-white/10 dark:bg-[#211D1A] dark:text-white">{stages.map((s) => <option key={s}>{s}</option>)}</select></label></div>
    <div className="mb-5 flex flex-wrap gap-2"><span className="rounded-full bg-[#FFF0F3] px-3 py-1.5 text-xs font-bold text-[#D94D62] dark:bg-[#E85D70]/10 dark:text-[#FF8EA0]">{visible.length} resources</span><span className="rounded-full bg-[#FAF8F6] px-3 py-1.5 text-xs font-semibold text-[#6B5D54] dark:bg-white/5 dark:text-[#CFC4BE]">{saved.length} saved</span></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((r) => <article key={r.id} className="rounded-[26px] border border-[#F2EDEA] bg-white p-5 transition hover:-translate-y-1 hover:shadow-lg dark:border-white/10 dark:bg-[#211D1A]"><div className="flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#FFF0F3] text-[#E85D70] dark:bg-[#E85D70]/15"><FileText size={18} /></div><button onClick={() => toggle(r.id)} className={saved.includes(r.id) ? 'text-[#E85D70]' : 'text-[#A8998E]'}><Bookmark size={19} fill={saved.includes(r.id) ? 'currentColor' : 'none'} /></button></div><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-[#FAF8F6] px-2.5 py-1 text-[10px] font-bold text-[#7B6B62] dark:bg-white/5 dark:text-[#CFC4BE]">{r.stage}</span><span className="rounded-full bg-[#FAF8F6] px-2.5 py-1 text-[10px] font-bold text-[#7B6B62] dark:bg-white/5 dark:text-[#CFC4BE]">{r.format}</span><span className="rounded-full bg-[#FAF8F6] px-2.5 py-1 text-[10px] font-bold text-[#7B6B62] dark:bg-white/5 dark:text-[#CFC4BE]">{r.time}</span></div><h2 className="mt-4 font-serif text-xl font-semibold text-[#332C28] dark:text-white">{r.title}</h2><p className="mt-2 text-sm leading-6 text-[#6B5D54] dark:text-[#CFC4BE]">{r.desc}</p><div className="mt-4 flex items-center justify-between text-xs"><span className="font-semibold text-[#A8998E]">{r.topic} • {r.difficulty}</span><button className="font-bold text-[#E85D70]">Open resource →</button></div></article>)}</div>
  </div></div>;
}
