import {Heart,MessageCircle,LockKeyhole,Users} from 'lucide-react';
const people=[
 {id:'alex',name:'Alex Morgan',country:'🇺🇸 United States'},
 {id:'sam',name:'Sam Taylor',country:'🇦🇺 Australia'},
 {id:'jamie',name:'Jamie Ellis',country:'🇬🇧 United Kingdom'},
 {id:'morgan',name:'Morgan Chen',country:'🇺🇸 United States'},
 {id:'riley',name:'Riley Santos',country:'🇦🇺 Australia'},
 {id:'taylor',name:'Taylor Brooks',country:'🇬🇧 United Kingdom'},
];
const conversations=[
 {author:0,topic:'Fieldwork & supervision',title:'A monthly review routine that finally clicked',body:'I organize sessions by supervisor, check my category totals, and bring three specific questions to our meeting. My documentation feels much less scattered now.',likes:28,replies:[{author:1,body:'A short checklist beside my log helps me keep the same routine every month.'},{author:4,body:'I like the three-question idea. It gives the review a clear focus.'}]},
 {author:1,topic:'Study strategies',title:'One example. One non-example.',body:'When two concepts feel similar, I write an everyday example and a non-example for each. Explaining the difference out loud is helping me understand the definitions.',likes:41,replies:[{author:2,body:'I use a little comparison table, then explain it without looking at my notes.'},{author:3,body:'Teaching it back to a study partner makes the gaps much easier to spot.'}]},
 {author:2,topic:'Wins & milestones',title:'Three focused study sessions this week',body:'A small win: I protected three realistic study blocks and finished with a short reflection each time. What helps you stay consistent when life gets busy?',likes:36,replies:[{author:0,body:'A realistic stopping time makes it easier for me to come back the next day.'},{author:5,body:'I plan the next small task before I close my notebook.'}]},
 {author:3,topic:'Exam preparation',title:'Making practice questions work harder',body:'I am keeping a notebook of why I chose an answer, what I overlooked, and what I will check next time. Reviewing the reasoning feels more useful than chasing a score.',likes:32,replies:[{author:1,body:'I group my notes by concept so patterns become easier to see.'},{author:2,body:'That reflection step is useful even when the answer was right.'}]},
 {author:4,topic:'Fieldwork & supervision',title:'Bring better questions to supervision',body:'I am trying to turn vague questions into specific ones: what did I observe, what information is missing, and what feedback would help me improve?',likes:25,replies:[{author:5,body:'Separating observations from interpretations is a helpful starting point.'},{author:0,body:'I keep a running question list so I do not forget during the meeting.'}]},
 {author:5,topic:'Starting the BCBA journey',title:'What would you tell your earlier self?',body:'My reminder would be to build a sustainable routine before collecting every possible study resource. I would love to hear the small habits that made your journey easier.',likes:47,replies:[{author:4,body:'A weekly check-in with myself has been more useful than an elaborate schedule.'},{author:3,body:'Choose one manageable next step, then repeat it consistently.'}]},
 {author:0,topic:'Ethics discussions',title:'Facts first, assumptions second',body:'For a de-identified ethics discussion, I separate known facts, assumptions, and questions that need more information. It keeps the conversation thoughtful and grounded.',likes:34,replies:[{author:2,body:'I also ask what information would change my interpretation.'},{author:5,body:'Keep identifying details out of the scenario, even when they seem minor.'}]},
 {author:1,topic:'Study accountability',title:'A calmer Sunday planning session',body:'I pick two study priorities, look at my actual availability, and leave breathing room. A shorter plan that I follow beats a perfect plan that I abandon.',likes:39,replies:[{author:4,body:'Leaving space for an unexpected day is such a practical habit.'},{author:0,body:'I use the same approach for preparing my supervision questions.'}]},
 {author:2,topic:'Coursework questions',title:'From a definition to an explanation',body:'My current challenge is explaining concepts in plain language without losing precision. How do you check that an explanation is both understandable and accurate?',likes:22,replies:[{author:3,body:'I compare my explanation with the course source after writing it from memory.'},{author:1,body:'A study partner can point out where I have skipped a step.'}]},
 {author:3,topic:'Research & resources',title:'Read with one clear question',body:'Before reading an article, I write down what I hope to understand. Afterward, I summarize the question, methods, findings, and limitations in a few sentences.',likes:31,replies:[{author:5,body:'The limitations deserve their own line. They are easy to overlook.'},{author:4,body:'I add one question to discuss with my supervisor afterward.'}]},
 {author:4,topic:'Wins & milestones',title:'Celebrating progress without comparing timelines',body:'Today’s win is feeling more organized than I did last month. Everyone’s coursework and fieldwork journey looks different, and I am learning to notice my own progress.',likes:54,replies:[{author:0,body:'Small improvements count. A steadier routine is real progress.'},{author:2,body:'This is a helpful reminder when a week feels slower than expected.'}]},
 {author:5,topic:'Career advice',title:'The questions I keep in my learning journal',body:'What did I learn? What feedback did I receive? What do I need to revisit? These three prompts help me notice patterns and prepare for my next supervision conversation.',likes:29,replies:[{author:1,body:'Simple enough to keep using even on a busy day.'},{author:3,body:'I would add one small action for the next week.'}]},
];
function Portrait({person,small=false}:{person:typeof people[number];small?:boolean}){
 return <img src={'/images/community/demo-'+person.id+'.jpg'} alt={'Generated portrait of fictional example member '+person.name} loading="lazy" decoding="async" width={small?30:44} height={small?30:44} className={(small?'h-[30px] w-[30px]':'h-11 w-11')+' shrink-0 rounded-full object-cover ring-2 ring-white dark:ring-[#332C28]'}/>;
}
export default function CommunityDemo(){return <section id="community-examples" aria-labelledby="community-examples-title" className="my-8 rounded-[28px] border border-[#F0DDE0] bg-[#FFF7F8] p-5 sm:p-7 dark:border-white/10 dark:bg-[#211D1A]">
 <div className="flex flex-wrap items-start justify-between gap-4"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#E85D70]/10 px-3 py-1.5 text-xs font-bold text-[#D94D62] dark:text-[#FF9BAB]"><Users size={14}/>Sample community activity</span><h2 id="community-examples-title" className="mt-3 font-serif text-3xl text-[#332C28] dark:text-white">Good conversations start here.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6B5D54] dark:text-[#CFC4BE]">Explore the kind of thoughtful conversations you can bring to Baker Commons. These members, portraits, posts, replies, and reaction counts are fictional examples, separate from real member activity.</p></div><span className="inline-flex items-center gap-2 rounded-full border border-[#E8DAD5] px-3 py-2 text-xs font-semibold text-[#6B5D54] dark:border-white/15 dark:text-[#CFC4BE]"><LockKeyhole size={13}/>Read-only examples</span></div>
 <div className="mt-5 flex flex-wrap items-center gap-3"><div className="flex -space-x-2">{people.map(person=><Portrait key={person.id} person={person} small/>)}</div><p className="text-xs font-semibold text-[#7B6B62] dark:text-[#CFC4BE]">6 example members · 12 conversations · 24 sample replies</p></div>
 <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{conversations.map((post,index)=><article key={post.title} className="flex flex-col rounded-2xl border border-[#F2EDEA] bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#171412]"><div className="flex items-center gap-3"><Portrait person={people[post.author]}/><div><div className="text-sm font-semibold text-[#332C28] dark:text-white">{people[post.author].name}</div><div className="mt-0.5 text-[11px] text-[#7B6B62] dark:text-[#BCAFA6]">{people[post.author].country}</div></div></div><span className="mt-4 text-[10px] font-bold uppercase tracking-[.12em] text-[#D94D62] dark:text-[#FF9BAB]">{post.topic}</span><h3 className="mt-1.5 font-serif text-xl font-semibold leading-snug text-[#332C28] dark:text-white">{post.title}</h3><p className="mt-3 text-sm leading-6 text-[#6B5D54] dark:text-[#CFC4BE]">{post.body}</p><div className="mb-4 mt-4 flex items-center gap-5 border-b border-[#F2EDEA] pb-3 text-xs font-semibold text-[#8B7C73] dark:border-white/10 dark:text-[#CFC4BE]" aria-label={'Example engagement: '+post.likes+' sample likes and '+post.replies.length+' sample replies'}><span className="inline-flex items-center gap-1.5"><Heart size={15} className="text-[#E85D70]"/>{post.likes} sample likes</span><span className="inline-flex items-center gap-1.5"><MessageCircle size={15}/>{post.replies.length} replies</span></div><div className="mt-auto space-y-3">{post.replies.map(reply=><div key={index+'-'+reply.author} className="flex items-start gap-2.5 rounded-xl bg-[#FFFAF7] p-3 dark:bg-white/5"><Portrait person={people[reply.author]} small/><p className="text-xs leading-5 text-[#6B5D54] dark:text-[#CFC4BE]"><strong className="mr-1 font-semibold text-[#332C28] dark:text-[#F5EEE9]">{people[reply.author].name}</strong>{reply.body}</p></div>)}</div></article>)}</div>
 <p className="mt-5 text-xs leading-5 text-[#7B6B62] dark:text-[#CFC4BE]">These examples stay read-only. Write your own discussion in the member area; sample likes and replies do not represent actual customer engagement.</p>
 </section>;}
