import {useState} from 'react';
import {Link} from 'react-router';
import {ArrowUpRight,Smartphone} from 'lucide-react';
const devices={phone:{label:'Phone · Fieldwork',src:'/images/mobile/fieldwork-phone-premium.jpg',alt:'A graphite smartphone showing the Fieldwork by Baker monthly dashboard with cream, pink and peach details',width:1145,height:1374},duo:{label:'Duo · Exam Lab',src:'/images/mobile/fieldwork-duo-premium.jpg',alt:'A Duo-inspired foldable smartphone showing the Fieldwork by Baker Exam Lab in a bright studio setting',width:1312,height:1199}};
export default function MobileAppAnnouncement(){
 const [selected,setSelected]=useState<'phone'|'duo'>('phone');const device=devices[selected];
 return <section aria-labelledby="mobile-app-title" className="my-8 overflow-hidden rounded-[2rem] border border-[#eaded4]" style={{backgroundColor:'#fffcf9',color:'#332c28'}}>
  <div className="grid items-center gap-3 px-6 py-8 sm:px-10 lg:grid-cols-[.9fr_1.1fr] lg:gap-8 lg:px-12 lg:py-10">
   <div className="relative z-10 max-w-lg py-4"><span className="inline-flex items-center gap-2 rounded-full border border-[#eaded4] px-3 py-1.5 text-xs" style={{color:'#8d6e58'}}><Smartphone size={14}/>A new chapter is coming</span><h2 id="mobile-app-title" className="mt-6 font-serif text-[clamp(2.25rem,4vw,3.75rem)] leading-[1.08] tracking-[-.035em]" style={{color:'#332c28'}}>Your journey.<br/>Soon, in your pocket.</h2><p className="mt-6 text-lg font-semibold sm:text-xl" style={{color:'#c4475b'}}>iOS and Android app coming soon!</p><p className="mt-4 max-w-sm text-sm leading-7" style={{color:'#79685d'}}>A little more freedom to move forward. Your fieldwork workspace is already available in your mobile browser.</p><Link to="/suggestions" className="mt-6 inline-flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold transition hover:brightness-95" style={{backgroundColor:'#f4c895',color:'#332c28'}}>Help shape what comes next<ArrowUpRight size={16}/></Link><p className="mt-5 text-[11px] leading-5" style={{color:'#918177'}}>Illustrative mobile app preview. Native apps are coming soon.</p></div>
   <div className="min-w-0"><div className="flex min-h-[380px] items-center justify-center sm:min-h-[440px] lg:min-h-[480px]"><img key={selected} src={device.src} alt={device.alt} width={device.width} height={device.height} loading="lazy" decoding="async" className="h-auto max-h-[540px] w-full object-contain"/></div><div className="mx-auto mt-4 flex w-fit flex-wrap justify-center gap-1 rounded-full border border-[#eaded4] bg-[#f6f0eb] p-1" role="group" aria-label="Choose mobile app preview">{(Object.keys(devices) as Array<keyof typeof devices>).map(key=><button key={key} type="button" aria-pressed={selected===key} onClick={()=>setSelected(key)} className="rounded-full px-4 py-2 text-xs font-semibold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#e85d70]" style={{backgroundColor:selected===key?'#ffffff':'transparent',color:selected===key?'#332c28':'#8d7b6e',boxShadow:selected===key?'0 2px 8px rgba(51,44,40,.06)':'none'}}>{devices[key].label}</button>)}</div></div>
  </div>
 </section>;
}
