import {useEffect,useRef,useState} from 'react';
import {Camera,UserRound} from 'lucide-react';
import {currentManagedToken} from '@/lib/managedSession';
async function photoRequest(body?:Record<string,unknown>){const token=await currentManagedToken();const response=await fetch('/api/profile-photo',{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});const result=await response.json();if(!response.ok)throw new Error('Your profile photo could not be saved. Please try again.');return result;}
async function preparePhoto(file:File){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw new Error('Choose a JPG, PNG, or WebP photo under 5 MB.');
 const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();if(image.naturalWidth<48||image.naturalHeight<48)throw new Error('Choose a photo at least 48 pixels wide and tall.');const size=Math.min(image.naturalWidth,image.naturalHeight);const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const context=canvas.getContext('2d');if(!context)throw new Error('Photo preview is unavailable.');context.drawImage(image,(image.naturalWidth-size)/2,(image.naturalHeight-size)/2,size,size,0,0,512,512);return canvas.toDataURL('image/png').split(',')[1];}finally{URL.revokeObjectURL(url);}
}
export default function ProfilePhotoSettings(){
 const [photo,setPhoto]=useState<string|null>(null),[draft,setDraft]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const input=useRef<HTMLInputElement>(null);const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;photoRequest().then(result=>{if(mounted.current)setPhoto(result.url);}).catch(()=>{if(mounted.current)setMessage('Photo settings could not load. Please refresh to try again.');});return()=>{mounted.current=false;};},[]);
 async function choose(file?:File){if(!file)return;setBusy(true);setMessage('');try{setDraft(await preparePhoto(file));}catch(error){setMessage(error instanceof Error?error.message:'Could not open photo.');}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function save(action:'upload'|'hide'){setBusy(true);setMessage('');try{const result=await photoRequest({action,...(action==='upload'?{png:draft}:{})});setPhoto(result.url);setDraft(null);window.dispatchEvent(new Event('fieldwork:profile-photo'));setMessage(action==='upload'?'Profile photo saved.':'Profile photo hidden. Previously shared photo links expire within 15 minutes.');}catch(error){setMessage(error instanceof Error?error.message:'Could not save photo.');}finally{setBusy(false);}}
 return <section className="mt-6 rounded-2xl border border-[#F2EDEA] bg-white p-6 dark:border-white/10 dark:bg-[#211D1A]"><h2 className="text-lg font-semibold">Your profile picture</h2><p className="mt-2 text-sm leading-6 text-[#6B5D54] dark:text-[#CFC4BE]">Use one profile photo across your Fieldwork account, navigation, dashboard, and community conversations. Saving it makes it visible to other verified Fieldwork members, including beside your posts and replies.</p><div className="mt-5 flex flex-wrap items-center gap-5">{draft||photo?<img src={draft?'data:image/png;base64,'+draft:photo!} alt="Your profile picture preview" width={88} height={88} className="h-[88px] w-[88px] rounded-full object-cover"/>:<span className="flex h-[88px] w-[88px] items-center justify-center rounded-full bg-[#FFF0F3] text-[#E85D70]"><UserRound size={32}/></span>}<div><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" aria-label="Choose your profile photo" disabled={busy} onChange={event=>void choose(event.target.files?.[0])} className="block max-w-full text-sm"/><p className="mt-2 text-xs text-[#6B5D54] dark:text-[#CFC4BE]">JPG, PNG, or WebP · up to 5 MB · centered square crop</p></div></div><div className="mt-4 flex gap-3">{draft&&<><button disabled={busy} onClick={()=>void save('upload')} className="inline-flex items-center gap-2 rounded-xl bg-[#E85D70] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><Camera size={16}/>{busy?'Saving…':'Save profile photo'}</button><button disabled={busy} onClick={()=>setDraft(null)} className="rounded-xl border px-4 py-2.5 text-sm">Cancel</button></>}{photo&&!draft&&<button disabled={busy} onClick={()=>void save('hide')} className="rounded-xl border px-4 py-2.5 text-sm">{busy?'Saving…':'Hide profile photo'}</button>}</div>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</section>;
}
