import { useState } from 'react';
import { ArrowRight, CheckCircle2, Download, FileText, Printer, Upload, X } from 'lucide-react';
const steps = [
  { title:'Open one month in Ripley', icon:FileText, image:'/guides/ripley-open-month.svg', alt:'Illustration: choose the month and organization, then show the dated entry list and descriptions.', text:'Sign in to Ripley yourself. Open the month dashboard for the correct organization. Show the full entry history, including the activity description under every session. Check that all entries have loaded—not only a filtered page.' },
  { title:'Print the detailed page to PDF', icon:Printer, image:'/guides/ripley-print-pdf.svg', alt:'Illustration of a print dialog: Save as PDF, all pages, readable full-width table.', text:'Use your browser’s Print command: ⌘P on Mac or Ctrl+P on Windows. Choose Save as PDF and All pages. The preview must include the first-page supervisor/organization details, each dated row and narrative, and the final totals row. Adjust scale or orientation if columns are cut off.' },
  { title:'Repeat for every month', icon:Download, image:'/guides/ripley-report-example.png', alt:'Screenshot of a rendered fictional detailed month PDF showing session rows and narrative text, not just a monthly verification form.', text:'Save a separate PDF for each month and organization, such as January-2026-Example-Clinic.pdf. This is the detailed month/history page—not the monthly verification form. Keep signed verification forms too, as separate supporting documents.' },
  { title:'Select all your monthly PDFs', icon:Upload, image:'/guides/baker-bulk-pdf.svg', alt:'Illustration: bulk select multiple monthly PDFs and review a separate reconciliation summary for each.', text:'Choose all the PDFs together below. Baker reads each session locally on this device, attaches the complete source PDF, maps supervisors and hour types, and checks every month against its printed totals. No AI is used to invent missing activities.' },
];
export default function RipleyPdfGuide(){
  const [zoom,setZoom]=useState<typeof steps[number]|null>(null);
  return <section className="rounded-3xl border border-[#F0D5DA] bg-gradient-to-br from-[#FFF5F7] to-white p-5 dark:border-[#E85D70]/25 dark:from-[#302026] dark:to-[#211D1A] sm:p-7" aria-labelledby="ripley-pdf-guide">
    <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#E85D70]"><FileText size={16}/>Ripley → Fieldwork by Baker</div>
    <h2 id="ripley-pdf-guide" className="mt-2 font-serif text-3xl">Bring every session. Pick up where you left off.</h2>
    <p className="mt-3 max-w-4xl text-sm leading-7 text-[#6B5D54] dark:text-[#CFC4BE]">Save a PDF of each month’s <strong>detailed entry history</strong> in Ripley, then bulk import those files here. Each original log session brings its dates, time range, decimal hours, categories, supervisor, organization and activity description—not just a monthly total.</p>
    <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{steps.map((step,index)=><article key={step.title} className="overflow-hidden rounded-2xl border border-[#F2EDEA] bg-white dark:border-white/10 dark:bg-[#211D1A]">
      <button type="button" onClick={()=>setZoom(step)} className="block w-full border-b border-[#F2EDEA] bg-[#FAF8F6] focus:outline-none focus:ring-2 focus:ring-inset focus:ring-[#E85D70] dark:border-white/10" aria-label={`Enlarge step ${index+1}: ${step.title}`}><img src={step.image} alt={step.alt} width="640" height="400" className="aspect-[8/5] h-auto w-full object-cover object-top" loading="lazy"/></button>
      <div className="p-4"><div className="flex items-center gap-2"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#E85D70] text-xs font-bold text-white">{index+1}</span><h3 className="font-semibold text-sm">{step.title}</h3></div><p className="mt-3 text-xs leading-6 text-[#6B5D54] dark:text-[#CFC4BE]">{step.text}</p></div>
    </article>)}</div>
    <div className="mt-4 rounded-2xl border border-[#CFE7D9] bg-[#F4FBF7] p-4 text-sm dark:border-green-700/30 dark:bg-green-900/10"><div className="flex items-center gap-2 font-semibold text-[#4B8C69] dark:text-green-200"><CheckCircle2 size={18}/>5. Review, reconcile, then continue tracking</div><p className="mt-2 leading-6 text-[#6B5D54] dark:text-[#CFC4BE]">Confirm each month’s session count and hour totals. Review any source overlaps or supervisor questions, then choose <strong>Import selected entries</strong>. Your imported sessions appear in Tracked entries and Audit History. Log your next new session normally—there is no need to recreate the old descriptions by hand.</p></div>
    <p className="mt-3 text-xs leading-6 text-[#8B7C73] dark:text-[#CFC4BE]">Steps 1, 2 and 4 use labelled illustrations. Step 3 shows a rendered example PDF with fictional records. Print controls may differ by browser. Before leaving any source platform, verify your full history and preserve an independent audit backup. Fields absent from a printable PDF—such as native entry IDs, prior edit history or separate attachments—cannot be recovered from that PDF.</p>
    <a href="#detailed-upload" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#E85D70] px-5 py-3 text-sm font-bold text-white">Choose monthly PDFs <ArrowRight size={16}/></a>
    {zoom&&<div role="dialog" aria-modal="true" aria-label={zoom.title} className="fixed inset-0 z-[160] flex items-center justify-center bg-black/65 p-4" onClick={()=>setZoom(null)} onKeyDown={e=>{if(e.key==='Escape')setZoom(null);}}><div className="relative max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-4 text-[#332C28]" onClick={e=>e.stopPropagation()}><button type="button" autoFocus className="absolute right-2 top-2 rounded-full bg-white p-2 shadow" aria-label="Close guide image" onClick={()=>setZoom(null)}><X size={20}/></button><img src={zoom.image} alt={zoom.alt} className="w-full rounded-xl"/><h3 className="mt-3 font-bold">{zoom.title}</h3><p className="mt-2 text-sm leading-6">{zoom.text}</p></div></div>}
  </section>;
}
