import {test,after} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'fieldwork-commons-'));const original=globalThis.fetch;after(async()=>{globalThis.fetch=original;await rm(dir,{recursive:true,force:true});});
const handlers={};for(const name of ['commons','profile-photo']){await build({entryPoints:['api/'+name+'.ts'],outfile:join(dir,name+'.mjs'),bundle:true,platform:'node',format:'esm'});handlers[name]=(await import(pathToFileURL(join(dir,name+'.mjs')))).default;}
process.env.SUPABASE_URL='https://fictional.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_fictional';
const uid='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333';let calls=[];
const response=()=>({code:0,setHeader(){},status(n){this.code=n;return this;},json(v){this.body=v;return this;}});
const req=(body,method='POST')=>({method,headers:{authorization:'Bearer fictional'},body});
function mock({confirmed=true,reject=null,photos=false,badSigned=false}={}){calls=[];globalThis.fetch=async(url,options)=>{if(url.endsWith('/auth/v1/user'))return Response.json({id:uid,email:'fictional@example.com',email_confirmed_at:confirmed?'2026-01-01':null});calls.push({url,options});if(reject)return Response.json({message:reject},{status:400});if(url.includes('community_photos'))return Response.json(photos?[{owner_id:uid,version:'v1'}]:[]);if(url.includes('/object/sign/'))return Response.json([{path:uid+'/avatar.png',signedURL:badSigned?'/object/sign/private-originals/secret.pdf?token=fictional':'/object/sign/community-avatars/'+uid+'/avatar.png?token=fictional'}]);return Response.json([]);};}
function png(w=512,h=512){const bytes=Buffer.alloc(45);Buffer.from([137,80,78,71,13,10,26,10]).copy(bytes);bytes.write('IHDR',12);bytes.writeUInt32BE(w,16);bytes.writeUInt32BE(h,20);return bytes.toString('base64');}
test('both endpoints reject anonymous and unverified callers before data access',async()=>{for(const h of Object.values(handlers)){for(const verified of [true,false]){mock({confirmed:verified});const r=response();await h(verified?{...req({action:'hide'}),headers:{}}:req({action:'hide'}),r);assert.equal(r.code,401);assert.equal(calls.length,0);}}});
test('post author, timestamps, and reaction totals cannot be supplied by client',async()=>{mock();const r=response();await handlers.commons(req({action:'post',id:other,title:'A question',body:'A thoughtful discussion.',forum:'General discussion',author_id:other,likes:999,created_at:'2099-01-01'}),r);assert.equal(r.code,200);assert.deepEqual(JSON.parse(calls[0].options.body),{p_id:other,p_title:'A question',p_body:'A thoughtful discussion.',p_forum:'General discussion'});assert.equal(calls[0].options.headers.Authorization,'Bearer fictional');});
test('database paid guard and rate limits propagate without exposing database details',async()=>{for(const [error,code] of [['PAID_SUBSCRIPTION_REQUIRED',403],['COMMUNITY_LIMIT',429],['COMMUNITY_CONFLICT',409]]){mock({reject:error+' private sql details'});const r=response();await handlers.commons(req({action:'like',postId:other,liked:true}),r);assert.equal(r.code,code);assert.equal(r.body.code,error);}});
test('invalid payloads and oversized content never reach community RPC',async()=>{for(const body of [{action:'like',postId:'../../private',liked:true},{action:'comment',id:uid,postId:other,body:'x'},{action:'post',id:other,title:'ok',body:'x'.repeat(20000),forum:'General'}]){mock();const r=response();await handlers.commons(req(body),r);assert.ok([400,413].includes(r.code));assert.equal(calls.length,0);}});
test('profile upload writes only the authenticated member fixed avatar path',async()=>{mock({photos:true});const r=response();await handlers['profile-photo'](req({action:'upload',png:png(),owner_id:other,path:'private-originals/secret.pdf'}),r);assert.equal(r.code,200);assert.ok(calls[0].url.endsWith('/community-avatars/'+uid+'/avatar.png'));assert.equal(calls[0].options.headers['Content-Type'],'image/png');assert.deepEqual(JSON.parse(calls[1].options.body),{p_visible:true});assert.ok(r.body.url.startsWith('https://fictional.supabase.co/storage/v1/object/sign/community-avatars/'+uid+'/avatar.png?'));});
test('malformed and oversized image dimensions fail before storage upload',async()=>{for(const photo of ['not-an-image',png(513,512),png(1,1),Buffer.alloc(1048577).toString('base64')]){mock();const r=response();await handlers['profile-photo'](req({action:'upload',png:photo}),r);assert.equal(r.code,400);assert.equal(calls.length,0);}});
test('hiding photo changes visibility without deleting storage or selecting another owner',async()=>{mock();const r=response();await handlers['profile-photo'](req({action:'hide',owner_id:other}),r);assert.equal(r.code,200);assert.equal(calls.length,1);assert.ok(calls[0].url.endsWith('/rpc/set_community_photo'));assert.deepEqual(JSON.parse(calls[0].options.body),{p_visible:false});});
test('photo response never forwards a signed URL for the private-originals bucket',async()=>{mock({photos:true,badSigned:true});const r=response();await handlers['profile-photo'](req(undefined,'GET'),r);assert.equal(r.code,200);assert.equal(r.body.url,null);});
