import {test,after} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'fieldwork-community-'));const original=globalThis.fetch;after(async()=>{globalThis.fetch=original;await rm(dir,{recursive:true,force:true});});
await build({entryPoints:['api/community.ts'],outfile:join(dir,'community.mjs'),bundle:true,platform:'node',format:'esm'});const {default:handler}=await import(pathToFileURL(join(dir,'community.mjs')));
process.env.SUPABASE_URL='https://fictional.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_fictional';
const response=()=>({code:0,setHeader(){},status(n){this.code=n;return this;},json(v){this.body=v;return this;}});const uid='22222222-2222-4222-8222-222222222222';let calls=[];
function mock(confirmed=true){calls=[];globalThis.fetch=async(url,options)=>{if(url.endsWith('/auth/v1/user'))return Response.json({id:uid,email:'fictional@example.com',email_confirmed_at:confirmed?'2026-01-01':null});calls.push({url,options});return Response.json(url.includes('community_profiles')?[]:[]);};}
const req=body=>({method:'POST',headers:{authorization:'Bearer fictional'},body});
test('anonymous and unverified callers cannot change visibility or activity',async()=>{for(const confirmed of [true,false]){mock(confirmed);const r=response();await handler(confirmed?{...req({action:'heartbeat'}),headers:{}}:req({action:'heartbeat'}),r);assert.equal(r.code,401);assert.equal(calls.length,0);}});
test('preferences use caller identity and reject invalid countries and implicit consent',async()=>{mock();let r=response();await handler(req({country:'US',showCountry:'true',sharePresence:false}),r);assert.equal(r.code,400);assert.equal(calls.length,0);r=response();await handler(req({owner_id:'attacker',country:'US',showCountry:true,sharePresence:false}),r);assert.equal(r.code,200);assert.deepEqual(JSON.parse(calls[0].options.body),{p_country:'US',p_show_country:true,p_share_presence:false});});
test('heartbeat ignores client-supplied activity timestamps and other user IDs',async()=>{mock();const r=response();await handler(req({action:'heartbeat',last_active_at:'2099-01-01',owner_id:'attacker'}),r);assert.equal(r.code,200);assert.equal(calls[0].options.body,'{}');assert.ok(calls[0].url.endsWith('/rpc/community_heartbeat'));});
