import {test,after} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(join(tmpdir(),'fieldwork-suggestions-'));const original=globalThis.fetch;after(async()=>{globalThis.fetch=original;await rm(dir,{recursive:true,force:true});});
await build({entryPoints:['api/suggestions.ts'],outfile:join(dir,'suggestions.mjs'),bundle:true,platform:'node',format:'esm'});const {default:handler}=await import(pathToFileURL(join(dir,'suggestions.mjs')));
process.env.SUPABASE_URL='https://fictional.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_fictional';process.env.RESEND_API_KEY='re_fictional';process.env.BAKER_NOTIFICATION_FROM='noreply@fieldworkbybaker.com';
const response=()=>({code:0,setHeader(){},status(n){this.code=n;return this;},json(v){this.body=v;return this;}});
const request=()=>({method:'POST',headers:{authorization:'Bearer fictional'},body:{category:'Performance or speed',message:'FICTIONAL TEST: improve the import page loading speed.',page:'Import',requestId:'11111111-1111-4111-8111-111111111111'}});
let sends;function mock(quota='RESERVED',confirmed=true){sends=[];globalThis.fetch=async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return Response.json({id:'22222222-2222-4222-8222-222222222222',email:'fictional@example.com',email_confirmed_at:confirmed?'2026-01-01':null});if(url.endsWith('/rpc/reserve_suggestion'))return Response.json(quota);if(url==='https://api.resend.com/emails'){sends.push(JSON.parse(opts.body));return Response.json({id:'fictional-delivery'});}throw Error('Unexpected request');};}
test('requires verified user and never sends anonymous/unconfirmed suggestions',async()=>{mock();let r=response();await handler({...request(),headers:{}},r);assert.equal(r.code,401);assert.equal(sends.length,0);mock('RESERVED',false);r=response();await handler(request(),r);assert.equal(r.code,401);assert.equal(sends.length,0);});
test('sends to both fixed inboxes with verified reply email, ignoring client recipient spoofing',async()=>{mock();const q=request();q.body.to=['attacker@example.com'];q.body.email='spoof@example.com';const r=response();await handler(q,r);assert.equal(r.code,200);assert.deepEqual(sends[0].to,['thebakersclt@gmail.com','Justin@bakerholdings.co']);assert.equal(sends[0].reply_to,'fictional@example.com');});
test('quota and conflicting retry cannot send email',async()=>{for(const [quota,status] of [['SUGGESTION_LIMIT',429],['SUGGESTION_CONFLICT',409]]){mock(quota);const r=response();await handler(request(),r);assert.equal(r.code,status);assert.equal(sends.length,0);}});
test('rejects oversized or invalid submissions before delivery',async()=>{mock();const q=request();q.body.message='x'.repeat(4001);const r=response();await handler(q,r);assert.equal(r.code,400);assert.equal(sends.length,0);});
